name: Unzip Nexium Browser

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip nexium-browser.zip to Root
        run: |
          unzip -o "nexium-browser.zip" -d .

      - name: Remove ZIP File
        run: |
          rm -f "nexium-browser.zip"

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet || git commit -m "Extract Nexium Browser to root"

          git push
